package action;

import common.Constants;
import fileio.ActionInputData;
import fileio.Writer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Action handler, stores relevant info for every action
 * that will be applied on the database.
 */
public class ActionCenter {
    private final List<Action> actions;

    public ActionCenter() {
        actions = new ArrayList<>();
    }

    /**
     * Constructor that uses the parsed list of actions and put them in a more
     * organised structure, where every action will be applied on the database.
     * @param commandsData List of actions that will be applied on the database
     *                     in raw format
     */
    public ActionCenter(final List<ActionInputData> commandsData) {
        this();

        for (ActionInputData action : commandsData) {
            Action temp = switch (action.getActionType()) {
                case Constants.COMMAND -> new Command(action.getActionId(), action.getUsername(),
                                                    action.getTitle(), action.getSeasonNumber(),
                                                    action.getType(), action.getGrade());
                case Constants.QUERY -> new Query(action.getActionId(), action.getObjectType(),
                                                    action.getNumber(), action.getFilters(),
                                                    action.getSortType(), action.getCriteria());
                case Constants.RECOMMENDATION -> new Recommendation(action.getActionId(),
                                    action.getUsername(), action.getType(), action.getGenre());
                default -> null;
            };

            this.actions.add(temp);
        }
    }

    /**
     * Redirects the commands to the method apply() from class Action
     * (which will return the output message generated by every action),
     * then creates a JSNOObject from the message and add it to the JSONArray.
     *
     * @param fileWriter Writer instance that has a method to create a JSONObject
     * @param arrayResult array of JSONObjects that stores the output
     */
    public final void applyActions(final Writer fileWriter, final JSONArray arrayResult) {
        actions.forEach(a -> {
            try {
                JSONObject output = fileWriter.writeFile(a.getActionId(), "", a.apply());
                arrayResult.add(output);
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
    }
}
